export enum InputNames {
  DISPLAY_NAME = 'display_name',
  EMAIL = 'email',
  FIRST_NAME = 'first_name',
  LOGIN = 'login',
  PASS = 'password',
  PASS_CONFIRM = 'password_confirm',
  PHONE = 'phone',
  SECOND_NAME = 'second_name',
  OLD_PASSWORD = 'oldPassword',
  NEW_PASSWORD = 'newPassword',
  SEARCH = 'search',
  MESSAGE = 'message',
  AVATAR = 'avatar',
}
